[project]
name = "fastapi-starter-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.4",
    "fastapi[standard]>=0.116.1",
    "ipykernel>=6.30.0",
    "sqlalchemy>=2.0.42",
]
